assets/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('assets.html', views.AssetListView.as_view(), name='assets_list'),
    path('asset-add.html',views.AssetAdd.as_view(),name='asset_add'),
    path('asset-detail-<int:pk>.html',views.AssetDetail.as_view(),name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),
    path('asset-all-del.html',views.AssetAllDel.as_view(),name='asset_all_del'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('portmap/list.html', views.PortMapListView.as_view(), name='portmap_list'),
    # 端口映射
    path('port/map/list/', views.PortMapListView.as_view(), name='port_map_list'),
    # 添加端口映射
    path('port/map/add/', views.AddPortMapView.as_view(), name='add_port_map'),
    # 删除映射记录
    path('port/delete/<int:p_id>/', views.DeletePortMapView.as_view(), name='delete_port'),
    # 修改映射记录
    path('port/map/change/<int:p_id>/', views.ChangePortMapView.as_view(), name='change_port'),
]

app_name = 'assets'

doc/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('doc_list.html', views.DocListView.as_view(), name='doc_list'),
    path('doc-detail.html-<int:pk>', views.DocDetailView.as_view(), name='doc_detail'),
    path('doc-update.html-<int:pk>', views.DocUpdateView.as_view(), name='doc_update'),

]

app_name = 'doc'

markdown/urls.py
from django import VERSION
from markdown.views import upload_image
if  VERSION<(1,9):
    from django.conf.urls import patterns, url
    urlpatterns = patterns('',
        url(r'^uploadimage/$', upload_image),
    )
else:
    from django.conf.urls import  url
    urlpatterns=[
        url(r'^uploadimage/$', upload_image),
    ]

rokin_cmdb/urls.py
from django.contrib import admin
from django.urls import path, include
import xadmin

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('admin/', admin.site.urls),
    path('', include('assets.urls')),
    path('doc/', include('doc.urls')),
    path('accounts/', include('accounts.urls'))
]

assets/models.py
from django.db import models
from django.urls import reverse


# 二级联动测试 国家地区
class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

# 资产
class assets(models.Model):
    assets_type_choices = (
        ('server', u'服务器'),
        ('vmser', u'虚拟机'),
        ('switch', u'交换机'),
    )
    assets_status_choices = (
        ('runing', u'在用'),
        ('stop', u'停用'),
    )
    # 资产状态
    assets_status = models.CharField(choices=assets_status_choices, max_length=100, default='runing', verbose_name='资产状态')
    # 资产类型
    assets_type = models.CharField(choices=assets_type_choices, max_length=100, default='server', verbose_name='资产类型')
    # 资产用途/描述
    assets_description = models.CharField(max_length=100, verbose_name='主机的用途', null=True, blank=True)
    # 资产名称
    hostname = models.CharField(max_length=64, verbose_name='资产名称', null=True, blank=True)
    # IP地址
    network_ip = models.GenericIPAddressField(verbose_name='IP地址')
    # 管理IP
    manage_ip = models.GenericIPAddressField(verbose_name='管理IP', null=True,blank=True)
    # 资产型号 硬件型号
    model = models.CharField(max_length=128, verbose_name='型号', null=True,blank=True)
    # 资产 系统类型 版本
    system = models.CharField(max_length=128,verbose_name='系统版本',null=True,blank=True)
    # 产品线 名
    pro_name = models.CharField(default='', max_length=64, verbose_name='项目名', blank=True)
    # 数据中心
    data_center = models.ForeignKey(to="data_centers", to_field='id', on_delete=models.SET_NULL, null=True, blank=True,verbose_name='数据中心')
    # 机柜
    cabinet = models.CharField(default='', max_length=64, verbose_name='机柜', blank=True)
    # 位置
    position = models.CharField(default='', max_length=64, verbose_name='位置', blank=True)
    # 登录用户名
    user_name = models.CharField(default='', max_length=32, verbose_name='登录用户名', blank=True)
    # 登录密码
    pass_word = models.CharField(default='', max_length=64, verbose_name='登录密码', blank=True)
    # SN
    sn = models.CharField(max_length=64,verbose_name='序列号', blank=True)
    # CPU
    cpu = models.CharField(default='', max_length=64,verbose_name='CPU', blank=True)
    # 内存
    memory = models.CharField(default=8, max_length=64, verbose_name='内存', blank=True)
    # 硬盘
    disk = models.CharField(default=300, max_length=256,verbose_name="硬盘", blank=True)
    # 备注
    ps = models.TextField(default='', max_length=1024,verbose_name="备注", blank=True)
    # 创建记录时间
    ctime= models.DateTimeField(auto_now_add=True,null=True,verbose_name='创建时间',blank=True)
    # 最后更新记录时间
    utime = models.DateTimeField(auto_now=True, null=True,verbose_name='更新时间',blank=True)

    # 二级联动测试
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='国家')
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='地区')


    class  Meta:
        # 数据库中指定 表名
        db_table ="asset"
        # 后台中显示的名称
        verbose_name="资产管理"
        # 去掉s 没有的话 在后台中会显示  资产管理s
        verbose_name_plural = '资产管理'

    def __str__(self):
        return self.network_ip

    # 这个函数 用来生成 url
    def get_absolute_url(self):
        return reverse('assets:asset_detail', kwargs={'pk': self.pk})


# 数据中心
class data_centers(models.Model):
    data_center_list = models.CharField(max_length=128, verbose_name='数据中心', null=True)


    class Meta:
        db_table = "data_centers"
        verbose_name = "数据中心"
        verbose_name_plural = '数据中心'

    def __str__(self):
        return self.data_center_list





########################################################################################################################
## 端口映射详情表
########################################################################################################################
class PortMap(models.Model):
    in_ip = models.ForeignKey(assets, verbose_name='内网IP', on_delete=models.CASCADE)
    in_port = models.SmallIntegerField(verbose_name='内网端口')
    out_ip = models.GenericIPAddressField(verbose_name='外网IP')
    out_port = models.SmallIntegerField(verbose_name='外网端口')
    ask_user = models.CharField(max_length=32, verbose_name='申请人')
    use_for = models.CharField(max_length=128, verbose_name='用途')
    start_time = models.DateField(verbose_name='开始时间')
    stop_time = models.DateField(verbose_name='结束时间')
    ps = models.TextField(blank=True, null=True, verbose_name='备注')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    class Meta:
        verbose_name = '端口映射表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.in_ip

assets/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .models import *
from django.views.generic import TemplateView, ListView, View, CreateView, UpdateView, DeleteView, DetailView,FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from .form import AssetForm, AddPortMapForm
import json
from django.conf import settings
from django.db.models import Q


class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'index.html')

# 资产列表类视图
class AssetListView(LoginRequiredMixin, ListView):
    model = assets
    context_object_name = 'asset_list'
    paginate_by = settings.DISPLAY_PER_PAGE
    template_name = 'assets/assets.html'
    queryset = assets.objects.all()
    ordering = ('id',)

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
        }
        kwargs.update(context)
        return super(AssetListView, self).get_context_data(**kwargs)

    ### 查询
    def get_queryset(self,*args,**kwargs):
        self.queryset = super().get_queryset()
        if  self.request.GET.get('name'):
            query = self.request.GET.get('name',None)
            # 主机名和IP地址的模糊查询
            queryset = self.queryset.filter(Q(network_ip__contains=query)| Q(hostname__contains=query)).order_by('id')
        else:
            queryset = super().get_queryset()
        return queryset

# 资产详情页
class AssetDetail(DetailView):
    model = assets
    template_name = 'assets/asset-detail.html'
    context_object_name = 'assets'

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
        }
        kwargs.update(context)
        return super(AssetDetail, self).get_context_data(**kwargs)


# 新增资产
class AssetAdd(CreateView):
    model = assets
    form_class = AssetForm
    template_name = 'assets/asset-add.html'

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
        }
        kwargs.update(context)
        return super(AssetAdd, self).get_context_data(**kwargs)


# # 更新资产信息
# class AssetUpdate(UpdateView):
#     model = assets
#     form_class = AssetForm
#     template_name = 'assets/asset-update.html'
#
#
#     def get_context_data(self, **kwargs):
#         asset_type = self.object.assets.assets_type
#         context = {
#             "asset_active": "active",
#             "asset_list_active": "active",
#             "asset_type": "asset_type",
#         }
#         kwargs.update(context)
#         return super(AssetUpdate, self).get_context_data(**kwargs)


# 更新资产信息
class AssetUpdate(LoginRequiredMixin, View):

    def get(self, request, pk):
        print(request.body)
        print(request.POST)
        asset = assets.objects.filter(id=pk)
        print(asset)
        context = {
            "asset": asset,
        }
        return render(request, 'assets/asset-update.html', context)

    def post(self, request, pk):
        change_host_form = AssetForm(request.POST)
        if change_host_form.is_valid():
            host = assets()
            host.id = int(pk)
            host.network_ip = request.POST.get('network_ip')
            host.hostname = request.POST.get('hostname')
            host.assets_description = request.POST.get('assets_description')
            host.assets_type = request.POST.get('assets_type')
            host.assets_status = request.POST.get('assets_status')
            host.system = request.POST.get('system')
            host.disk = int(request.POST.get('disk'))
            host.memory = int(request.POST.get('memory'))
            host.ps = request.POST.get('ps')
            host.save()
            assets_list = assets.objects.all()
            context = {
                "asset_list": assets_list
            }

            return render(request, 'assets/assets.html', context)

            #return HttpResponse('{"status":"success", "msg":"记录修改成功！"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"记录修改失败！"}', content_type='application/json')




# 删除资产
class AssetAllDel(LoginRequiredMixin,View):

    model = assets

    def post(self, request):
        ret = {'status': True, 'error': None, }
        try:
            if  request.POST.get('nid') :
                id = request.POST.get('nid', None)
                assets.objects.get(id=id).delete()
            else:
                print(1)
        finally:
            return HttpResponse(json.dumps(ret))

# 二级联动 获取城市 测试
def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'assets/city_dropdown_list_options.html', {'cities': cities})



### 端口映射列表视图
class PortMapListView(ListView):
    model = PortMap
    context_object_name = 'portmap_list'
    template_name = 'assets/portmap-list.html'

    def get_context_data(self, **kwargs):
        assets_list = assets.objects.all()
        context = {
            "asset_active": "active",
            "port_map_list_active": "active",
            "assets": assets_list
        }
        kwargs.update(context)
        return super(PortMapListView, self).get_context_data(**kwargs)





########################################################################################################################
## 添加映射视图
########################################################################################################################
class AddPortMapView(LoginRequiredMixin, View):
    def post(self, request):
        add_portmap_form = AddPortMapForm(request.POST)
        if add_portmap_form.is_valid():
            # 判断记录是否存在
            if PortMap.objects.filter(in_ip=request.POST.get('in_ip')).filter(in_port=request.POST.get('in_port')):
                return HttpResponse('{"status":"fail", "msg":"映射已存在！"}', content_type='application/json')

            # 添加新记录
            portmap = PortMap()
            portmap.in_ip_id = request.POST.get('in_ip')
            portmap.in_port = request.POST.get('in_port')
            portmap.out_ip = request.POST.get('out_ip')
            portmap.out_port = request.POST.get('out_port')
            portmap.ask_user = request.POST.get('ask_user')
            portmap.use_for = request.POST.get('use_for')
            portmap.start_time = request.POST.get('start_time')
            portmap.stop_time = request.POST.get('stop_time')
            portmap.ps = request.POST.get('ps')
            portmap.save()

            return HttpResponse('{"status":"success", "msg":"映射记录添加成功！"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"映射记录添加失败！"}', content_type='application/json')


########################################################################################################################
## 删除映射视图
########################################################################################################################
class DeletePortMapView(LoginRequiredMixin, View):
    def post(self, request, p_id):
        try:
            ports = PortMap.objects.get(id=int(p_id))
            ports.delete()
            return HttpResponse('{"status":"success", "msg":"映射记录删除成功！"}', content_type='application/json')
        except Exception as e:
            return HttpResponse('{"status":"fail", "msg":"映射记录删除失败！"}', content_type='application/json')


########################################################################################################################
## 修改映射视图
########################################################################################################################
class ChangePortMapView(LoginRequiredMixin, View):
    def post(self, request, p_id):
        change_portmap_form = AddPortMapForm(request.POST)
        if change_portmap_form.is_valid():
            # 删除旧的记录
            old_ports = PortMap.objects.get(id=int(p_id))
            old_ports.delete()
            # 添加新的记录
            portmap = PortMap()
            portmap.in_ip_id = request.POST.get('in_ip')
            portmap.in_port = request.POST.get('in_port')
            portmap.out_ip = request.POST.get('out_ip')
            portmap.out_port = request.POST.get('out_port')
            portmap.ask_user = request.POST.get('ask_user')
            portmap.use_for = request.POST.get('use_for')
            portmap.start_time = request.POST.get('start_time')
            portmap.stop_time = request.POST.get('stop_time')
            portmap.ps = request.POST.get('ps')
            portmap.save()
            return HttpResponse('{"status":"success", "msg":"映射记录修改成功！"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"映射记录修改失败！"}', content_type='application/json')

templates/assets/assets.html
{% extends "base.html" %}
{% block  title %}资产信息{% endblock %}

{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产信息</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'assets:index' %}">主页</a>
                </li>
                <li>
                    <a href="{% url 'assets:assets_list' %}">资产管理</a>
                </li>
                <li class="active">
                    <strong>资产信息</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>资产信息</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">


                            <form id="cha" class="form-horizontal" action="{% url 'assets:assets_list' %}" method="GET">
                                {% csrf_token %}
                                <div class="col-md-2"><input type="text" class="form-control" name="name" placeholder="主机名、IP" required></div>

                                <button class="btn btn-sm btn-primary" type="submit">查询</button>

                                <a class="btn btn-sm btn-default btn-add" data-toggle="modal"
                                   href="{% url 'assets:asset_add' %}">
                                    <i class="fa fa-plus"></i> 添加主机
                                </a>
{#                                <a class="btn btn-sm btn-default btn-add asset_all_del" data-toggle="modal">#}
{#                                    <i class="fa fa-plus"></i> 批量删除#}
{#                                </a>#}
                                <a class="btn btn-sm btn-default btn-add" data-toggle="modal">
                                    <i class="fa fa-plus"></i> 导出全部
                                </a>
                            </form>

                            <form id="del_form_asset_all" class="form-horizontal  ">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>IP</th>
                                        <th>主机名</th>
                                        <th>用途</th>
                                        <th>状态</th>
                                        <th>分类</th>
                                        <th>所属组</th>
                                        <th>系统</th>
                                        <th>动作{{ error_performance }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for row in asset_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center"><a
                                                    href="{{ row.get_absolute_url }}">{{ row.network_ip }}</a>
                                            </td>
                                            <td class="center">{{ row.hostname }}</td>
                                            <td class="center">{{ row.assets_description }}</td>
                                            {% if row.assets_status == "runing" %}
                                                <td class="center">在用</td>
                                            {% else %}
                                                <td class="center">停用</td>
                                            {% endif %}
                                            {% if row.assets_type == "server" %}
                                                <td class="center">物理服务器</td>
                                            {% elif row.assets_type == "vmser" %}
                                                <td class="center">虚拟机</td>
                                            {% else %}
                                                <td class="center">交换机</td>
                                            {% endif %}
                                            <td class="center">{{ row.product_line.name }}</td>
                                            <td class="center">{{ row.system }}</td>
                                            <td><a class="btn btn-primary  btn-xs "
                                                   href="{% url  "assets:asset_update"  row.id %}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  asset_del" data-toggle="modal"
                                                   data-target="#myModal1">删除
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>

                                <div><!--分页相关 -->
                                    <center>

                                        <ul class="pagination">
                                            <li><a href="{% url "assets:assets_list" %}?page=1">首页 </a></li>
                                            {% if  page_obj.has_previous %}
                                                <li>
                                                    <a href="{% url "asset:assets_list" %}?page={{ page_obj.previous_page_number }}&{{ search_data }}">
                                                        上一页 </a></li>
                                            {% else %}
                                                <li class="disabled"><a> 上一页 </a></li>
                                            {% endif %}

                                            {% for p in paginator.page_range %}
                                                {% if  search_data %}  <!-- 判断是否是搜索分页-->
                                                    {% if p == page_obj.number %}
                                                        <li class="active"><a
                                                                href="{% url "assets:assets_list" %}?page={{ p }}&{{ search_data }}"> {{ p }} </a>
                                                        </li>
                                                    {% else %}
                                                        <li>
                                                            <a href="{% url "assets:assets_list" %}?page={{ p }}&{{ search_data }}"> {{ p }} </a>
                                                        </li>
                                                    {% endif %}
                                                {% else %}
                                                    {% if p == page_obj.number %}
                                                        <li class="active"><a
                                                                href="{% url "assets:assets_list" %}?page={{ p }}"> {{ p }} </a>
                                                        </li>
                                                    {% else %}
                                                        <li>
                                                            <a href="{% url "assets:assets_list" %}?page={{ p }}"> {{ p }} </a>
                                                        </li>
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}


                                            {% if  page_obj.has_next %}
                                                <li>
                                                    <a href="{% url "assets:assets_list" %}?page={{ page_obj.next_page_number }}&{{ search_data }}">
                                                        下一页 </a></li>
                                            {% endif %}
                                            <li>
                                                <a href="{% url "assets:assets_list" %}?page={{ page_obj.paginator.num_pages }}">尾页 </a>
                                            </li>
                                            <li><span style="color: #0a0a0a">总: &nbsp;{{ page_obj.paginator.num_pages }} 页 </span>
                                            </li>

                                        </ul>
                                    </center>
                                </div> <!--分页相关 -->
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>



    {% block footer-js %}


        <script>
            $(function () {

                // 删除资产
                $(document).on('click', '.asset_del', function () {
                    var id = $(this).parent().parent().attr('id');
                    swal({
                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "{% url 'assets:asset_all_del'%}",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });

                });

            });

        </script>


    {% endblock %}

{% endblock %}

templates/assets/city_dropdown_list_options.html
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}