accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/loginx.html'), name='login'),

]

assets/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('assets.html', views.AssetListView.as_view(), name='assets_list'),
    path('asset-add.html',views.AssetAdd.as_view(),name='asset_add'),
    path('asset-detail-<int:pk>.html',views.AssetDetail.as_view(),name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),
    path('asset-all-del.html',views.AssetAllDel.as_view(),name='asset_all_del'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('portmap/list.html', views.PortMapListView.as_view(), name='portmap_list'),
    # 端口映射
    path('port/map/list/', views.PortMapListView.as_view(), name='port_map_list'),
    # 添加端口映射
    path('port/map/add/', views.AddPortMapView.as_view(), name='add_port_map'),
    # 删除映射记录
    path('port/delete/<int:p_id>/', views.DeletePortMapView.as_view(), name='delete_port'),
    # 修改映射记录
    path('port/map/change/<int:p_id>/', views.ChangePortMapView.as_view(), name='change_port'),
]

app_name = 'assets'

doc/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('doc_list.html', views.DocListView.as_view(), name='doc_list'),
    path('doc-detail.html-<int:pk>', views.DocDetailView.as_view(), name='doc_detail'),
    path('doc-update.html-<int:pk>', views.DocUpdateView.as_view(), name='doc_update'),

]

app_name = 'doc'

markdown/urls.py
from django import VERSION
from markdown.views import upload_image
if  VERSION<(1,9):
    from django.conf.urls import patterns, url
    urlpatterns = patterns('',
        url(r'^uploadimage/$', upload_image),
    )
else:
    from django.conf.urls import  url
    urlpatterns=[
        url(r'^uploadimage/$', upload_image),
    ]

rokin_cmdb/urls.py
from django.contrib import admin
from django.urls import path, include
import xadmin

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('admin/', admin.site.urls),
    path('', include('assets.urls')),
    path('doc/', include('doc.urls')),
    path('accounts/', include('accounts.urls'))
]

templates/_css.html
{% load  static %}

<link href=" {% static  "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static  "font-awesome/css/font-awesome.css" %}" rel="stylesheet">

<link href="{% static  "css/animate.css" %}" rel="stylesheet">
<link href="{% static "css/style.css"  %} " rel="stylesheet">

<link href="{% static "css/datatables.min.css"%} "   rel="stylesheet">

<link href="{% static "css/plugins/select2/select2.min.css"%} "   rel="stylesheet">
<link href="{% static "bootstrap_date/bootstrap-select.css"%} "   rel="stylesheet">


<link href="{% static  "css/plugins/sweetalert/sweetalert.css"%}" rel="stylesheet">

<link href="{% static "css/animate.css"%}" rel="stylesheet">
<link href="{% static "css/style.css"%}" rel="stylesheet">
<link href="{% static 'bootstrap_date/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">

<!-- Toastr style -->
<link  href="{% static  "css/plugins/toastr/toastr.min.css" %}"  rel="stylesheet">

templates/_footer.html
  <div class="footer">
            <div class="pull-right">
               <strong>rokin</strong>
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2017-2020
            </div>
        </div>

templates/_js.html
{% load  static %}

<script src="{% static  "js/jquery-3.1.1.min.js"%}"></script>
<script src="{% static  "js/bootstrap.min.js"%}"></script>
<script src="{% static  "js/plugins/metisMenu/jquery.metisMenu.js"%}"></script>
<script src="{% static  "js/plugins/slimscroll/jquery.slimscroll.min.js"%}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static  "js/inspinia.js"%} "></script>
<script src="{% static  "js/plugins/pace/pace.min.js"%}"></script>


<script src="{% static  "js/datatables.min.js" %}"></script>


<script src="{% static  "js/plugins/select2/select2.full.min.js" %}"></script>
<script src="{% static "bootstrap_date/bootstrap-select.js" %}"></script>

<!-- Sweet alert -->
<script src="{% static  "js/plugins/sweetalert/sweetalert.min.js" %}"></script>


 <!-- Toastr script -->
<script src="{% static  "js/plugins/toastr/toastr.min.js"%}"></script>
<script src="{% static 'bootstrap_date/moment-with-locales.min.js' %}"></script>
<script src="{% static 'bootstrap_date/bootstrap-datetimepicker.min.js' %}"></script>

<script type="text/JavaScript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
</script>





<!-- Page-Level Scripts -->
<script>
   $(document).ready(function () {
        $('.dataTables-example').DataTable({

            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
            "order": [[1, 'desc']],
            columnDefs: [{
                'targets': [0],    //都默认不排序
                'orderable': false
            }],


            dom: '<"html5buttons"B>lTfgitp,',

            buttons: [],
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "全部"]]
        });


    });


       $("#CheckedAll").click(function () {
        if ($(this).is(":checked")) {
            $("[name=id]:checkbox").prop("checked", true);
        } else {
            $("[name=id]:checkbox").prop("checked", false);
        }
    });





    </script>

templates/_nav.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong
                                    class="font-bold">{{ user }}</strong>

                             </span> <span class="text-muted text-xs block">
                                {% ifequal  user.is_superuser  1 %}
                                    管理员 {% else %} 普通用户 {% endifequal %}
                                <b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="#">修改密码</a></li>
                        <li><a href="{% url 'accounts:logout' %}">登出</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    Ops
                </div>
            </li>
            <li>
                <a href="{% url 'assets:index' %}"><i class="fa fa-th-list"></i> <span class="nav-label">首页</span>
                </a>
            </li>
            <li class="{{ asset_active }}">
                <a href="#"><i class="fa fa-drivers-license"></i> <span class="nav-label">资产管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ asset_list_active }}"><a href="{% url 'assets:assets_list' %}">资产信息</a></li>
                    <li class="{{ port_map_list_active }}"><a href="{% url 'assets:port_map_list' %}">端口映射</a></li>
                    <li class="{{ asset_config_list_active }}"><a href="#">资产配置</a></li>
                </ul>
            </li>
            <li class="{{ doc_active }}">
                <a href="#"><i class="fa fa-drivers-license"></i> <span class="nav-label">文档管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ doc_jishu_active }}"><a href="/xadmin">后台</a></li>
                    <li class="{{ doc_yunwei_active }}"><a href="#">运维记录</a></li>
                    <li class="{{ doc_zhishiku_active }}"><a href="{% url 'doc:doc_list' %}">知识库</a></li>
                </ul>
            </li>
        </ul>ß
    </div>
</nav>

templates/_navbar-static-top.html
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            欢迎 {{ user }} 使用 Rokin-cmdb系统 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <li>
                <a href="{% url 'accounts:logout' %}">
                    <i class="fa fa-sign-out"></i> 注销
                </a>
            </li>
        </ul>
    </nav>
</div>

templates/base.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block  title %}{% endblock %}</title>

    {% include  "_css.html" %}
    {% include  "_js.html" %}
    {% block header-css %}
    {% endblock %}

</head>

<body>

<div id="wrapper">

    {% include "_nav.html" %}

    <div id="page-wrapper" class="gray-bg">
        {% include  "_navbar-static-top.html" %}

        {% block page-content %}


        {% endblock %}
        {% include  "_footer.html" %}

    </div>
</div>



{% block footer-js %}
{% endblock %}





</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block  title %}Rokin-cmdb | 首页{% endblock %}

{% block header-css %}

{% endblock %}


{% block page-content %}

    {# 顶部导航栏 #}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>主页</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'assets:index' %}">主页</a>
                </li>
                <li class="active">
                    <strong>面板</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

{% endblock %}


{% block footer-js %}
    <script>

        toastr.options = {
            "closeButton": true,
            "debug": false,
            "progressBar": true,
            "preventDuplicates": true,
            "positionClass": "toast-top-right",
            "onclick": null,
            "showDuration": "400",
            "hideDuration": "1000",
            "timeOut": "7000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        ;

        toastr.success("欢迎来到MY_CMDB!", "欢迎")

    </script>
{% endblock %}

templates/users_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block web_title %}
    {% endblock web_title %}
  </title>
  <link rel="shortcut icon" href="" type="image/x-icon">

  <!-- css -->
  <link href="{% static 'users/css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'users/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'users/css/other-style.css' %}" rel="stylesheet">
  <link href="{% static 'users/css/app.css' %}" rel="stylesheet">

  <!-- 其他css -->
  {% block other_css %}
    <style>
      .captcha {
        float: right;
      }
    </style>
  {% endblock other_css %}

  <!-- js -->
  <script src="{% static 'users/js/jquery.js' %}"></script>
  <script src="{% static 'users/js/bootstrap.js' %}"></script>

</head>

<body class="" style="background-color: #E0E0E0">

<!-- 页面主体 -->
{% block web_content %}
{% endblock web_content %}

<!-- 其他js -->
{% block other_js %}
{% endblock other_js %}

</body>
</html>